# Generated by Django 4.0.4 on 2022-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='institution',
        ),
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='newuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
